version: '3.8'
services:

  database:
    image: mysql
    container_name: helloworld_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: helloworld
    ports:
      - 127.0.0.1:3306:3306
    volumes:
      - db_storage:/var/lib/mysql
    restart: always

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: helloworld_frontend
    ports:
      - 127.0.0.1:4200:4200
    volumes:
      - ../../frontend/:/home/node
    command: >
      /bin/sh -c "npm install && ng serve --host 0.0.0.0; exit 0"

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: helloworld_backend
    depends_on:
      - database
    environment:
      DB_URL: mysql+mysqlconnector://root:toor@database/helloworld
    ports:
      - 127.0.0.1:5000:5000
    volumes:
      - ../../backend/:/home/python
    command: >
      /bin/sh -c "pip install --no-cache-dir -r requirements.txt && python app.py"
    restart: always   # reiniciar porque mysql no esta listo al construir, funciona bin cuando las imagenes ya están creadas

volumes:
  db_storage:
