name: Build, push and deploy

on:
  push:
    branches:
      - 'main'

jobs:

  build_push_deploy:

    permissions:
      deployments: write

    runs-on: ubuntu-latest
    
    steps:
   
      - name: CHECKOUT REPOSITORY
        uses: actions/checkout@v2

      - name: SET UP PATH FILTERS
        uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            backend:
              - 'backend/**'
              - 'docker/build/Dockerfile.backend'
            frontend:
              - 'frontend/**'
              - 'docker/build/Dockerfile.frontend'
      
      - name: LOGIN TO DOCKERHUB
        uses: docker/login-action@v3
        if: steps.filter.outputs.backend == 'true' || steps.filter.outputs.frontend == 'true'
        with:
          username: tomnoir
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      
      - name: BUILD BACKEND
        uses: docker/build-push-action@v5 
        id: build_backend
        if: steps.filter.outputs.backend == 'true'
        with:
          push: true
          file: ./docker/build/Dockerfile.backend
          tags: tomnoir/helloworld-backend:latest
      
      - name: BUILD FRONTEND
        uses: docker/build-push-action@v5 
        id: build_frontend
        if: steps.filter.outputs.frontend == 'true'
        with:
          push: true
          file: ./docker/build/Dockerfile.frontend
          tags: tomnoir/helloworld-frontend:latest

      - name: CREATE DEPLOYMENT
        uses: chrnorm/deployment-action@v2
        if: steps.build_backend.outcome == 'success' || steps.build_frontend.outcome == 'success'
        id: create_deployment
        with:
          token: ${{ github.token }}
          environment-url: ${{ secrets.DEPLOY_URL }}
          environment: production

      - name: DEPLOY TO PRODUCTION SERVER
        uses: appleboy/ssh-action@v1.0.3
        id: deploy
        if: steps.create_deployment.outcome == 'success'
        with:
          host: ${{ secrets.PROD_HOST }}
          username: ${{ secrets.PROD_USERNAME }}
          key: ${{ secrets.PROD_KEY }}
          port: ${{ secrets.PROD_PORT }}
          script: bash services/deploy.sh

      - name: UPDATE DEPLOYMENT STATUS (SUCCESS)
        if: steps.create_deployment.outcome == 'success' && steps.deploy.outcome == 'success'
        uses: chrnorm/deployment-status@v2
        with:
          token: ${{ github.token }}
          environment-url: ${{ secrets.DEPLOY_URL }}
          state: 'success'
          deployment-id: ${{ steps.deployment.outputs.deployment_id }}
      
      - name: UPDATE DEPLOYMENT STATUS (FAILURE)
        if: steps.deployment.outcome == 'success' && failure()
        uses: chrnorm/deployment-status@v2
        with:
          token: ${{ github.token }}
          environment-url: ${{ secrets.DEPLOY_URL }}
          state: 'failure'
          deployment-id: ${{ steps.deployment.outputs.deployment_id }}
